#CloudBuild
steps:
- name: 'ubuntu'
  args: ['echo', 'hey', 'ubuntu']
- name: 'node:latest'
  args: ['bash', '-c', 'cd node']
  args: ['npm', 'install']
  args: ['npm', 'run', 'build']
  args: ['npm', 'run', 'test']
  args: ['echo', 'hey', 'node']
- name: 'maven'
  args: ['mvn', 'clean', 'install', '-D', 'skipTests']
  args: ['echo', 'hey', 'maven']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=jaffrezouludovic --password=832b8a8b-a623-4cb8-8084-ef0b9972bdac']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker build -t jaffrezouludovic/testcicd .']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push jaffrezouludovic/testcicd']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  dir: 'node'
  args: ['-c', 'cd node']
  args: ['-c', 'docker build -t jaffrezouludovic/testcicd .']
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: 'bash'
  dir: 'node'
  args: ['-c', 'cd node']
  args: ['-c', 'docker push jaffrezouludovic/testcicd']
#- name: 'docker'
#  args: ['login', '-u', 'jaffrezouludovic','-p','832b8a8b-a623-4cb8-8084-ef0b9972bdac']
#- name: 'docker'
#  args: ['build', '-t', 'jaffrezouludovic:testcicd', '.']
#- name: 'docker'
#  args: ['push', 'jaffrezouludovic:testcicd']

#- name: 'gcr.io/cloud-builders/docker'
#  args: ['login', '-u', 'jaffrezouludovic','-p','832b8a8b-a623-4cb8-8084-ef0b9972bdac']
#  args: ['build', '-t', 'gcr.io/august-jigsaw-301016/jaffrezouludovic', '.' ]