#CloudBuild
steps:
- name: 'ubuntu'
  args: ['echo', 'hey', 'ubuntu']
- name: 'node'
  args: ['npm', 'install']
  args: ['npm', 'run']
  args: ['npm', 'build']
  args: ['echo', 'hey', 'node']
- name: 'maven'
  args: ['mvn', 'clean', 'install', '-D', 'skipTests']
  args: ['echo', 'hey', 'maven']
- name: 'docker'
  entrypoint: 'bash'
  args: ['-c', 'docker login --username=jaffrezouludovic --password=832b8a8b-a623-4cb8-8084-ef0b9972bdac']
  args: ['-c', 'docker build -t jaffrezouludovic/testcicd:1.0.1 .']
- name: 'docker'
  entrypoint: 'bash'
  args: ['-c', 'docker push jaffrezouludovic/testcicd']