#Test
steps:
- name: 'ubuntu'
  args: ['echo', 'hey', 'ubuntu']
- name: 'node'
  args: ['npm', 'run']
  args: ['npm', 'build']
- name: 'maven'
  args: ['mvn', 'clean', 'install', '-D', 'skipTests']
- name: 'docker'
  args: ['docker', 'login', '-u', 'jaffrezouludovic', '832b8a8b-a623-4cb8-8084-ef0b9972bdac']
  args: ['docker', 'build', '-t', 'jaffrezouludovic/testcicd:1.0.1', '.']
  args: ['docker', 'push', 'jaffrezouludovic/testcicd:1.0.1']

